version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      - MYSQL_DATABASE=pamw
      - MYSQL_ROOT_PASSWORD=root
    security_opt:
      - seccomp:unconfined